import { ReactNode } from "react";
import NavBar from "../components/NavBar";
import { Roboto } from 'next/font/google';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
    keywords: 'tienda, online, ecommerce',
}

const roboto = Roboto({
    weight:["300", "400", "500", "700"],
    style: ["italic", "normal"],
    subsets: ["latin"],

})

interface LayoutProps {
    children: ReactNode;
}

export default function Layout({ children }: LayoutProps) { 
    return (
        <html lang="en">
            <body className={roboto.className}>
                <NavBar />
            {children}
            </body>
        </html>
    )
}